trigger:
  branches:
    include:
      - main
      - dev

variables:
  backend_rg: dontestingrg
  backend_storage: dontestingstorageacct
  container_name: tfstate
  tf_version: '1.5.7'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Dev
  displayName: "Terraform Plan and Apply - Dev"
  jobs:
  - job: terraform
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - script: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list
        apt update && apt install terraform -y
        terraform version
      displayName: 'Install Terraform'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mynewproject'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: 'environments/dev'
        inlineScript: |
          terraform init -backend-config="resource_group_name=$(backend_rg)" \
                         -backend-config="storage_account_name=$(backend_storage)" \
