trigger:
  branches:
    include:
      - main
      - dev

variables:
  backend_rg: dontestingrg
  backend_storage: dontestingstorageacct
  container_name: tfstate
  tf_version: '1.5.7'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Dev
  displayName: "Terraform Plan and Apply - Dev"
  jobs:
  - job: terraform
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '$(tf_version)'
      displayName: 'Install Terraform'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure subscription 1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(System.DefaultWorkingDirectory)/ZELECTRIC/environments/dev'
        inlineScript: |
          terraform init -backend-config="resource_group_name=$(backend_rg)" \
                         -backend-config="storage_account_name=$(backend_storage)" \
                         -backend-config="container_name=$(container_name)" \
                         -backend-config="key=dev.terraform.tfstate"

          terraform plan -var-file="terraform.tfvars"
          terraform apply -auto-approve -var-file="terraform.tfvars"
